# Generated by Django 5.0.6 on 2024-10-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valor', models.IntegerField(null=True)),
                ('codigo', models.CharField(max_length=10, null=True)),
                ('tabla', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(default='HABILITADO', max_length=25, null=True)),
            ],
            options={
                'db_table': 'parametricas',
                'ordering': ['id'],
            },
        ),
    ]
