# Generated by Django 5.0.6 on 2024-12-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametricas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrica',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
