# Generated by Django 5.0.6 on 2024-12-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentraa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rentraa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'test',
            },
        ),
        migrations.DeleteModel(
            name='ConsultantRenca',
        ),
    ]
