# Generated by Django 5.0.6 on 2024-12-16 17:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(max_length=150)),
                ('account_name', models.CharField(max_length=150)),
                ('unit_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='BOB', max_length=10)),
                ('state', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renewal_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('abbreviation', models.CharField(max_length=1)),
                ('type', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_code', models.CharField(max_length=10, unique=True)),
                ('province_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('code_id', models.IntegerField(blank=True, null=True)),
                ('geographic_code', models.CharField(blank=True, max_length=3, null=True)),
                ('code_renca', models.CharField(blank=True, max_length=10, null=True)),
                ('code_renca_company', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_code', models.CharField(max_length=10, unique=True)),
                ('ulot_name', models.CharField(max_length=255)),
                ('ulot_capital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ine_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mepf_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mepf_acronym', models.CharField(blank=True, max_length=50, null=True)),
                ('mepf_code', models.CharField(blank=True, max_length=50, null=True)),
                ('eta', models.CharField(blank=True, max_length=50, null=True)),
                ('tioc_aioc', models.CharField(blank=True, max_length=255, null=True)),
                ('macroregion', models.CharField(blank=True, max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_deleted', models.BooleanField(default=False)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='parameters.province')),
            ],
            options={
                'db_table': 'municipalities',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='parameters.state'),
        ),
    ]
